Audiocontext
codex-team/codex.music pull request #11
Opened 2019-10-17 16:53 UTC by overkam

added audiocontextmanager class (with comments)

2019-10-17 17:51 UTC, neSpecc requested changes

2019-10-17 17:51 UTC, neSpecc commented on webAudioContextManager.ts
> +	private _contex: AudioContex;
не описано свойство

2019-10-17 17:51 UTC, neSpecc commented on webAudioContextManager.ts
> + *  Class representing an AudioContextManager
два пробела

2019-10-17 17:51 UTC, neSpecc commented on webAudioContextManager.ts
> +	 *  Create AudioContext
лишний пробел

2019-10-17 17:51 UTC, neSpecc commented on webAudioContextManager.ts
> +	private _contex: AudioContex;
не верная табуляция

2019-10-17 17:51 UTC, neSpecc commented on webAudioContextManager.ts
> +		if (this._contex == undefined) this._context = new AudioContext;
if надо написать полностью

2019-10-17 17:51 UTC, neSpecc commented on webAudioContextManager.ts
> +		if (this._contex == undefined) this._context = new AudioContext;
не верно написан конструктор

2019-10-17 17:51 UTC, neSpecc commented on webAudioContextManager.ts
> + *  Class representing an AudioContextManager
не понятное описание класса

2019-10-22 22:59 UTC, daibogh requested changes
файл переписать, перед каждым коммитом делай yarn build или npm run build, чтобы eslint все пробелы и табуляции за тебя поправил.
любые комментарии проверяй дважды, можно даже в google translate закидывать
файл, подозреваю, ни разу не компилили - так делать не надо, проверяй сделанную работу

2019-10-22 22:59 UTC, daibogh commented on webAudioContextManager.ts
> + * @typedef {object} AudioContextConfig
зачем ты объявляешь свой тип AudioContextConfig? удаляй

2019-10-22 22:59 UTC, daibogh commented on webAudioContextManager.ts
> + * @property {object} AudioContext - part of a melody
тоже удали

2019-10-22 22:59 UTC, daibogh commented on webAudioContextManager.ts
> +class AudioContextManager.ts {
убери .ts в конце строки

2019-10-22 22:59 UTC, daibogh commented on webAudioContextManager.ts
> +	 * @param  {AudioContextConfig} settings - melody configuration obj
зачем в конструктор передается settings параметр, если он нигде не используется?
что надо сделать - либо:
1) убирай его из конструктора(и из jsdoc)
2) сделай с ним что-то в конструкторе
мне больше нравится 1 вариант

2019-10-22 22:59 UTC, daibogh commented on webAudioContextManager.ts
> +		private _context: AudioContext;
эту строчку вынести из конструктора. Пример, как объявляются private поля в typescript классах:
class Animal {

    private name: string;

    constructor(theName: string) { this.name = theName; }

}

2019-10-22 22:59 UTC, daibogh commented on webAudioContextManager.ts
> +	 * @retuts {AudioContext} this._context
@retuts не существует в jsdoc, исправь
в pull request-ах не должно быть никаких опечаток.

2019-10-22 22:59 UTC, daibogh commented on webAudioContextManager.ts
> +		if (this._context == undefined)
во-первых, лучше использовать ===,
во-вторых, здесь наверно можно переписать на (!this._context)

2019-10-22 22:59 UTC, daibogh commented on webAudioContextManager.ts
> +			{this._context = new AudioContext};
{
  this._context = new AudioContext();
}

2019-10-22 22:59 UTC, daibogh commented on webAudioContextManager.ts
> +export default new AudioContextManager.ts();
убрать .ts
в конце файла должна быть одна пустая строчка

2019-10-25 13:24 UTC, neSpecc requested changes
лишние файлы

2019-10-25 16:48 UTC, ilyamore88 commented
Closes #6

2019-10-25 17:18 UTC, neSpecc approved these changes

2019-10-28 14:42 UTC, nikmel2803 approved these changes

2019-11-01 08:45 UTC, daibogh approved these changes

2019-11-01 13:19 UTC, merged