Add melody module
codex-team/codex.music pull request #12
Opened 2019-10-17 17:03 UTC by ilyamore88

2019-10-17 17:05 UTC, ilyamore88 commented
- Необходимо добавить метод для проверки корректности передаваемой ноты;
- Необходимо добавить возможность изменять `defaultLength` ноты.

2019-10-18 21:01 UTC, neSpecc requested changes
- не указаны возвращаемые значения у методов
- не указана область видимости у методов

2019-10-18 21:04 UTC, neSpecc requested changes

2019-10-18 21:04 UTC, neSpecc commented on src/modules/melody.ts
> +   * Default note length
надо указать единицы измерения

2019-10-22 15:10 UTC, neSpecc requested changes

2019-10-22 15:10 UTC, neSpecc commented on src/modules/melody.ts
> +      if (note.length === 1 && note === '.') {
эти два ифа можно упросить и объединить в один

2019-10-22 15:10 UTC, neSpecc commented on src/modules/melody.ts
> +      if (note.length === 4) {
тоже желательно упростить и убрать дублирование кода

2019-10-22 15:10 UTC, neSpecc commented on src/utils/noteFrequencies.ts
> +  [32.70, 39.71, 41.20, 43.65, 49.00, 55.00, 61.74], // octave 1
точно нужно зашивать именно эти восемь октав? может вычислять частоту динамически?

2019-10-23 20:20 UTC, neSpecc requested changes

2019-10-23 20:20 UTC, neSpecc commented on src/modules/melody.ts
> +      } else {
тут не нужен else, можно сдвинуть блок влево

2019-10-23 20:26 UTC, neSpecc approved these changes

2019-10-24 15:48 UTC, nikmel2803 commented on src/modules/melody.ts
> +      return 440 * Math.pow(2, ((noteInOctave + (octave * 12) + 1) - 70) / 12);
давай 440 вынесем в константу и задокументируем что это

2019-10-24 15:48 UTC, nikmel2803 commented on src/modules/melody.ts
> +   * Note name
```suggestion
   * Note name (e.g. 'A4', 'C3#')
```

2019-10-24 15:48 UTC, nikmel2803 commented on src/modules/melody.ts
> +      case 'C':
может сделать `enum` вида
```ts
enum Notes {
  C = 1,
  D = 3
  ...
}
```
вдруг ещё где нибудь пригодится

2019-10-24 15:48 UTC, nikmel2803 commented on src/utils/error/validationError.ts
> +/**
давай папку перенесём на уровень выше

2019-10-24 17:03 UTC, nikmel2803 approved these changes

2019-10-25 09:57 UTC, merged