added some base classes
codex-team/codex.music pull request #14
Opened 2019-10-22 22:31 UTC by daibogh

resolves #10

2019-10-23 19:28 UTC, neSpecc requested changes

2019-10-23 19:28 UTC, neSpecc commented on src/index.ts
> +export { ChilloutAudio, TracksManager, EffectTypes, InstrumentTypes, Melody };
экспортировать нужно только сам класс ChilloutAudio, все остальное это приватные вещи

2019-10-23 19:28 UTC, neSpecc commented on src/index.ts
> +  get tracksManager(): TracksManager {
это можно сделать приватным свойством

2019-10-23 19:28 UTC, neSpecc commented on src/index.ts
> +  private _tracksManager: TracksManager;
нет описания свойства

2019-10-23 19:28 UTC, neSpecc commented on src/index.ts
> +  init() {
не указано область видимости и возвращаемое значение. И почему не использовать вместо init конструктор?

2019-10-23 19:28 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +  private _isPlaying: boolean;
не описаны свойства

2019-10-23 19:28 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> + * class provides track configuration
```suggestion
 * Class provides track configuration
```

2019-10-23 19:28 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> + * class providing track's configuration and playback
```suggestion
 * Class providing track's configuration and playback
```

2019-10-23 19:28 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +  private _interval: number;
нижние подчёркивания не нужны

2019-10-23 19:28 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +   * sets musical instrument
С большой буквы надо везде сделать

2019-10-23 19:28 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +  setInstrument(instrumentType:string) {
не указан тип возвращаемого значения

2019-10-23 19:28 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +  setInstrument(instrumentType:string) {
```suggestion
  setInstrument(instrumentType: string) {
```

2019-10-23 19:28 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +  setInstrument(instrumentType:string) {
и область видимости метода

2019-10-31 21:02 UTC, neSpecc requested changes

2019-10-31 21:02 UTC, neSpecc commented on src/index.ts
> +  private get tracksManager(): TracksManager {
приватные методы должны быть под конструктором. Вообще за это отвечает какое-то правило в eslint

2019-10-31 21:02 UTC, neSpecc commented on src/index.ts
> +  destroy() {
```suggestion
  public destroy(): void {
```

2019-10-31 21:02 UTC, neSpecc commented on src/index.ts
> +export { ChilloutAudio };
лучше у класса сразу написать `export default class ChilloutAudio {`

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +   * sets musical instrument
все еще актуально

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +   * @param instrumentType
не описан параметр

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +   * @this {TrackBuilder}
```suggestion
```

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +   * creating track with default configuration
с большой буквы

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +      return (this.instrument = new InstrumentTypes[instrumentType]());
this.instrument надо объявить как свойство класса

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +  setInstrument(instrumentType: string): (string) => Instrument {
при объявлении методов класса не надо использовать arrow functions

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +  setInstrument(instrumentType: string): (string) => Instrument {
не указана область видимости и возвращаемое значение

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +  getInstrument() {
здесь и далее — 
1) указать область видимости
2) указать тип возвращаемого значения
3) описать параметры в jsdoc — что они делают, для чего нужны

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +    this.melody = new Melody(melody);
не объявлено свойство класса

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +   * @param melody
не описан параметр

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +   * @param interval
не описан параметр

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +   * @param effectType
не описаны параметры

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +   * @param index
не описан параметр

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +   * @param gain
не описаны параметры

2019-10-31 21:02 UTC, neSpecc commented on src/modules/TracksManager.ts
> +   * @param initialTracksNumber {number} default number of tracks being added in tracks field
эту логику лучше убрать пока. добавим потом, если будет нужно

2019-10-31 21:02 UTC, neSpecc commented on src/modules/melody/Melody.ts
> + * Melody class
не понятно, что это за класс. Модуль мелодий мы уже смерджили

2019-10-31 21:06 UTC, daibogh commented on src/index.ts
> +  destroy() {
зачем явно объявлять сигнатуру возвращаемого значения, если это вычисляется автоматически??

2019-10-31 21:12 UTC, ilyamore88 reviewed
Где-то при объявлении приватных полей используется `_` в начале названия, где-то нет. Разве мы начинаем названия приватных полей с `_`?

2019-10-31 21:13 UTC, daibogh commented on src/modules/TrackBuilder.ts
> +  setInstrument(instrumentType: string): (string) => Instrument {
зачем public свойствам указывать модификатор доступа?

2019-10-31 21:13 UTC, daibogh commented on src/modules/TrackBuilder.ts
> +  getInstrument() {
зачем public свойствам указывать модификатор доступа?

2019-10-31 21:14 UTC, daibogh commented on src/modules/TrackBuilder.ts
> +    this.melody = new Melody(melody);
объявлено

2019-10-31 21:25 UTC, daibogh commented
> Где-то при объявлении приватных полей используется `_` в начале названия, где-то нет. Разве мы начинаем названия приватных полей с `_`?

В одних местах описаны поля через get конструкцию, в каких-то - через getMethod

2019-11-01 04:23 UTC, neSpecc requested changes
- убрать все методы из классов
- убрать все, связанное с Effects, Instruments

2019-11-01 04:23 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +export class TrackBuilder {
этот класс лучше назвать просто Track, так локаничнее

2019-11-01 04:23 UTC, neSpecc commented on src/modules/TrackBuilder.ts
> +export class TrackBuilder {
все методы пока надо выпилить, кроме конструктора

2019-11-01 04:23 UTC, neSpecc commented on .eslintignore
> +/example/
не относится к задаче, надо убрать

2019-11-01 04:23 UTC, neSpecc commented on src/modules/TracksManager.ts
> +  get tracks() {
все методы и свойства надо убрать из этого реквеста

2019-11-01 07:06 UTC, daibogh commented on .eslintignore
> +/example/
в example ведь свой eslint, лучше сразу проставить, чтоб vue не трогало

2019-11-01 07:29 UTC, neSpecc requested changes

2019-11-01 07:29 UTC, neSpecc commented on .eslintignore
> +/example/
@ilyamore88 согласуй этот момент

2019-11-01 07:29 UTC, neSpecc commented on src/index.ts
> +  destroy() {
чтобы если метод будет усложняться, не пришлось типизировать старый код, а только новый. Лучше все сразу типизировать и указать public/private

2019-11-01 07:29 UTC, neSpecc commented on src/index.ts
> +  private _tracksManager: TracksManager;
нижние подчеркивания в ts не нужны, тк мы и так явно указываем область видимости

2019-11-01 07:29 UTC, neSpecc commented on src/index.ts
> +  private _tracksManager: TracksManager;
это фишка была актуальна в js, да и то давненько

2019-11-01 07:29 UTC, neSpecc commented on src/modules/Track.ts
> +export class Track {
тут не нужны default?

2019-11-01 07:29 UTC, neSpecc commented on src/index.ts
> +  get tracksManager(): TracksManager {
геттер не нужен, тк это свойство приватное, к нему и так можно будет обратиться через `this.tracksManager` внутри класса (только нижнее подчеркивание нужно убрать)

2019-11-01 07:29 UTC, neSpecc commented on src/index.ts
> +   * @return {Void}
в ts return лучше типизировать явно, а не с помощью jsdoc. А вот параметры методов имеют описания, поэтому к ним мы пишем доки

2019-11-01 07:43 UTC, neSpecc approved these changes

2019-11-01 16:18 UTC, ilyamore88 approved these changes

2019-11-04 09:27 UTC, merged