[#18]Added track implementation
codex-team/codex.music pull request #20
Opened 2019-11-07 18:55 UTC by daibogh

resolves #18

2019-11-07 19:10 UTC, ilyamore88 requested changes
Почти нигде нет типов возвращаемых значений

2019-11-07 19:10 UTC, ilyamore88 commented on src/modules/Track.ts
> +   * this property implements audio source logic
Комментарии с маленькой буквы здесь и далее

2019-11-07 19:10 UTC, ilyamore88 commented on src/modules/instrument.ts
> +  playNote(note:MelodyNote, when: number) {
Нет модификатора доступа

2019-11-07 19:13 UTC, neSpecc requested changes

2019-11-07 19:13 UTC, neSpecc commented on src/modules/instrument.ts
> +  private readonly instrumentOptions: GainNode;
название не самое удачное для GainNode

2019-11-07 19:13 UTC, neSpecc commented on src/modules/instrument.ts
> +   * @param wave
?

2019-11-07 19:13 UTC, neSpecc commented on src/modules/instrument.ts
> +  public stop(when = audioContextManager.getAudioContext().currentTime) {
параметр не описан и не указан тип

2019-11-07 19:54 UTC, ilyamore88 commented on src/modules/Melody.ts
> +  private notes: string
Нет доков, нет `;`

2019-11-08 10:59 UTC, ilushaR commented on src/modules/Track.ts
> +  private isConfigured = false
надо поставить `;`

2019-11-08 10:59 UTC, ilushaR commented on src/modules/SineWaveInstrument.ts
> +class SineWaveInstrument extends Instrument {
предлагаю назвать, класс  и файл PeriodicWaveInstrument

2019-11-08 10:59 UTC, ilushaR commented on src/modules/instrument.ts
> +    };
3 строчка точно нужна?

2019-11-08 11:07 UTC, PeterBaranov commented on src/modules/SineWaveInstrument.ts
> +class SineWaveInstrument extends Instrument {
класс Instrument является сущностью, в котором задается волна

2019-11-11 11:31 UTC, neSpecc requested changes

2019-11-11 11:31 UTC, neSpecc commented on src/index.ts
> +  const melody = new Melody('A4 A5 D3 e4 d4 f8 a6 b3 c2 A5 A4');
это все нужно перенести в публичный метод play класса `ChilloutAudio`. Чтобы он принимал `melody:string` и `instrument: string`

2019-11-11 11:31 UTC, neSpecc commented on src/index.ts
> +document.getElementById('play').onclick = () => {
js код должен быть в index.html или сразу в example/

2019-11-11 11:31 UTC, neSpecc commented on src/modules/SineWaveInstrument.ts
> +class SineWaveInstrument extends Instrument {
@ilushaR но ведь любой инструмент работает через PeriodicWave

2019-11-11 11:31 UTC, neSpecc commented on src/modules/SineWaveInstrument.ts
> +    super('Sine wawe instument');
опечатка + надо вынести константы названий инструментов куда-то

2019-11-11 11:31 UTC, neSpecc commented on src/modules/Track.ts
> +  /**
```suggestion

  /**
```

2019-11-11 11:31 UTC, neSpecc commented on src/modules/Track.ts
> +   * @property {number} timeOffset - time to recognize when the note should be played
```suggestion
   * Time to recognise when the note should be played
```

2019-11-11 11:31 UTC, neSpecc commented on src/modules/Track.ts
> +    if (!this.isConfigured) this.configure();
не по стайлгайду

2019-11-11 11:31 UTC, neSpecc commented on src/modules/instrument.ts
> +      .getAudioContext().createGain();
эти вещи надо перенести в публичные методы AudioContextManager

2019-11-11 21:34 UTC, ilyamore88 commented
Closes #21

2019-11-12 19:30 UTC, neSpecc approved these changes

2019-11-12 21:26 UTC, ilyamore88 approved these changes

2019-11-14 05:07 UTC, merged