Create instruments modules
codex-team/codex.music pull request #30
Opened 2019-11-21 19:02 UTC by ilushaR

2019-11-21 21:22 UTC, ilyamore88 requested changes
Предлагаю добавить папку `modules/instruments`, в которой мы будем хранить наши кастомные инструменты

2019-11-21 21:28 UTC, ilyamore88 approved these changes

2019-11-21 21:28 UTC, ilyamore88 commented on src/modules/instruments/Horn.ts
> + * Class representing an horn instrument
```suggestion
 * Class representing a horn instrument
```

2019-11-22 04:04 UTC, neSpecc approved these changes

2019-11-22 04:07 UTC, neSpecc reviewed
Абстрактный инструмент я бы тоже в эту папку перенес

2019-11-22 16:11 UTC, merged