Looped play melody
codex-team/codex.music pull request #31
Opened 2019-11-22 18:02 UTC by ilushaR

2019-11-26 15:00 UTC, ilyamore88 requested changes

2019-11-26 15:00 UTC, ilyamore88 commented on src/ChilloutAudio.ts
> +   * Method for start  playing track
```suggestion
   * Method for start playing track
```

2019-11-26 15:00 UTC, ilyamore88 commented on src/modules/Melody.ts
> +  public defaultLength = 300;
Зачем делать это поле публичным?

2019-11-26 15:00 UTC, ilyamore88 commented on src/modules/Melody.ts
> +   * getter for duration melody
```suggestion
   * Getter for duration melody
```

2019-11-26 15:00 UTC, ilyamore88 commented on src/modules/Melody.ts
> +   * getter for duration melody
Не прописан `@return`

2019-11-26 15:00 UTC, ilyamore88 commented on src/modules/Melody.ts
> +    return this.defaultLength * this.noteList.length;
Если у тебя кастомная длина ноты, то такая формула не сработает

2019-11-26 15:00 UTC, ilyamore88 commented on src/modules/Track.ts
>      this.instrument.node.connect(audioContextManager.getAudioContext().destination);
Притяни мастер и пофикси конфликты

2019-11-27 11:05 UTC, neSpecc requested changes

2019-11-27 11:05 UTC, neSpecc commented on src/modules/Melody.ts
> +  public get durationMelody(): number {
лучше просто duration

2019-11-27 11:05 UTC, neSpecc commented on src/modules/Track.ts
> +  private isPlay: number;
isPlaying

2019-11-27 11:05 UTC, neSpecc commented on src/modules/Track.ts
> +   * Track status (track is playing or not)
описание не соответствует хранимому значению

2019-11-27 11:05 UTC, neSpecc commented on src/modules/Track.ts
> +  private isPlay: number;
название подразумевает хранение boolean, но там хранится интервал

2019-11-27 11:50 UTC, neSpecc approved these changes

2019-11-27 11:51 UTC, ilyamore88 approved these changes

2019-11-27 11:52 UTC, merged