Track volume control
codex-team/codex.music pull request #38
Opened 2019-11-27 23:01 UTC by ilushaR

2019-11-27 23:04 UTC, ilyamore88 requested changes

2019-11-27 23:04 UTC, ilyamore88 commented on src/modules/Track.ts
> +    this.instrument.outputNode.connect(this.gainNode);
Этот connect надо делать в play

2019-11-28 04:17 UTC, ilyamore88 requested changes

2019-11-28 04:17 UTC, ilyamore88 commented on src/ChilloutAudio.ts
> +    console.log(volume);
?

2019-11-28 04:17 UTC, ilyamore88 commented on src/modules/Track.ts
> +  protected readonly gainNode: GainNode;
Это поле private

2019-11-28 04:39 UTC, ilyamore88 approved these changes

2019-11-28 11:06 UTC, neSpecc approved these changes

2019-11-28 15:20 UTC, merged