create instruments module
codex-team/codex.music pull request #7
Opened 2019-10-16 20:12 UTC by ilushaR

2019-10-16 20:21 UTC, neSpecc requested changes

2019-10-16 20:21 UTC, neSpecc commented on instruments.js
> +                sin = [0, 1, 4 / 9, 4 / 9, 4 / 9, 6 / 9, 5 / 9, 6 / 9, 5 / 9, 3 / 9, 3 / 9, 2 / 9, 1 / 9, 2 / 9, 2 / 9, 1 / 9];
предлагаю сразу вынести это в какой-то объект с конфигом

2019-10-16 20:21 UTC, neSpecc commented on instruments.js
> +    setWave() {
код надо продокументировать по jsdoc: класс, методы, параметры, возвращаемые значения и

2019-10-16 20:21 UTC, neSpecc commented on instruments.js
> +class Instruments extends Audio {
а что за класс Audio?

2019-10-16 20:21 UTC, neSpecc commented on instruments.js
> +    constructor(instrument) {
параметр не задокументирован

2019-10-16 20:21 UTC, neSpecc commented on instruments.js
> +        let sin = [];
что означает sin?

2019-10-16 20:25 UTC, ilushaR commented on instruments.js
> +class Instruments extends Audio {
Аудио контекста

2019-10-16 21:13 UTC, ilushaR commented on instruments.js
> +                sin = [0, 1, 4 / 9, 4 / 9, 4 / 9, 6 / 9, 5 / 9, 6 / 9, 5 / 9, 3 / 9, 3 / 9, 2 / 9, 1 / 9, 2 / 9, 2 / 9, 1 / 9];
Что именно - switch или значения инструментов?

2019-10-17 15:25 UTC, neSpecc requested changes

2019-10-17 15:25 UTC, neSpecc commented on instruments.js
> +                sin = [0, 1, 4 / 9, 4 / 9, 4 / 9, 6 / 9, 5 / 9, 6 / 9, 5 / 9, 3 / 9, 3 / 9, 2 / 9, 1 / 9, 2 / 9, 2 / 9, 1 / 9];
значения

2019-10-17 15:25 UTC, neSpecc commented on instruments.js
> +class Instruments extends Audio {
у нас нет такого класса

2019-11-01 11:55 UTC, neSpecc requested changes

2019-11-01 11:55 UTC, neSpecc commented on instrument.ts
> +/**
файл должен быть встроен в структуру проекта, а не лежать в корне

2019-11-01 11:55 UTC, neSpecc commented on instrument.ts
> +    instrument: string;
свойства надо описать и указать модификаторы доступа

2019-11-01 11:55 UTC, neSpecc commented on instrument.ts
> +class Instrument {
класс надо экспортировать

2019-11-01 11:55 UTC, neSpecc commented on instrument.ts
> +    setWave(): void {
у методов надо указать модификаторы доступа

2019-11-01 11:55 UTC, neSpecc commented on instrument.ts
> +      }
надо продумать, как инструмент будет подключаться к дорожке

2019-11-01 11:59 UTC, neSpecc requested changes

2019-11-01 11:59 UTC, neSpecc commented on instrument.ts
> +     * @param {string} instrument - Name of the instrument.
тогда лучше назвать name

2019-11-01 11:59 UTC, neSpecc commented on instrument.ts
> +      this.waves = {
я бы сделал Instrument абстрактным классом и еще сделал потомка SineWaveInstrument, который будет определять форму волны


instrument.ts
```ts
abstract class Instrument {
///...
}
```

instrument-sine-wave.ts

```ts
class SineWaveInstrument extends Instrument {
///...
}
```

2019-11-01 16:26 UTC, ilyamore88 requested changes
Исправь размеры отступов, у тебя первый таб на 4 пробела (должны быть все на два). В конце файлов нет пустой строки. Запусти eslint, чтобы он пофиксил это.

2019-11-01 16:26 UTC, ilyamore88 commented on src/modules/instrument-periodic-wave.ts
> +        // this.oscillator.setPeriodicWave(this.context.createPeriodicWave(real, image));
Закомментированный код надо убрать из файла

2019-11-01 20:46 UTC, neSpecc requested changes

2019-11-01 20:46 UTC, neSpecc commented on src/modules/instrument-periodic-wave.ts
> +   * @property {number[]} wave - Current wave
док для свойства wave надо написать над свойством wave

2019-11-24 11:58 UTC, closed without merging