create filter
codex-team/codex.music pull request #8
Opened 2019-10-16 21:28 UTC by Kirilllert

добавлен фильтр Gain (Усилитель)

2019-10-16 21:29 UTC, neSpecc requested changes

2019-10-16 21:29 UTC, neSpecc commented on filters.js
> +const gainNode = context.createGain();
давай добавим класс-обертку

2019-10-16 21:29 UTC, neSpecc commented on filters.js
> +gainNode.gain.value = 0.4;
значение надо расхардкодить и передавать как параметр в конструктор класса или метод

2019-10-17 15:25 UTC, neSpecc requested changes

2019-10-17 15:25 UTC, neSpecc commented on filters.js
> +  createNode() {
методы не задокументированы, смотри usejsdoc.org

2019-10-17 15:25 UTC, neSpecc commented on filters.js
> +  createNode() {
вернее доки не там находятся

2019-10-17 15:25 UTC, neSpecc commented on filters.js
> +/** Class create a new filter(gain). */
надо написать, что делает этот фильтр

2019-10-17 15:25 UTC, neSpecc commented on filters.js
> +/** Class create a new filter(delay). */
надо написать, что делает этот фильтр

2019-10-17 21:57 UTC, neSpecc requested changes
Давай сделаем абстрактный класс Filter и отнаследуем от него все фильтры.

filter.ts
```
class Filter {}
```

filter-gain.ts
```
class GainFilter extends Filter {}
```

filter-noise.ts
```
class NoiseFilter extends Filter {}
```

весь общий код будет содержаться в абстрактном классе Filter, а весь специфичный в потомках.

2019-10-17 22:00 UTC, neSpecc requested changes

2019-10-17 22:00 UTC, neSpecc commented on filters.js
> + * @ allFiltrers
в описании класса надо написать, зачем он нужен

2019-10-17 22:00 UTC, neSpecc commented on filters.js
> +     * Create a  gain filter.
описание метода должно быть над объявлением метода, читай usejsdoc

2019-10-17 22:00 UTC, neSpecc commented on filters.js
> +    delayNode.delayTime.value = 2;
что такое 2? погугли magic number

2019-10-17 22:00 UTC, neSpecc commented on filters.js
> +    delayNode.delayTime.value = 2;
там и дальше по коду такие магические числа

2019-10-29 21:01 UTC, nikmel2803 reviewed
- папку `.idea` коммитить вообще не надо (притяни мастера, там уже прописано нужное правило для игнора этой папки)
- `package-lock.json` не нужен, потому что мы используем `yarn` вместо `npm`
А почему тут вообще лежат js файлы? Проект же на TS

2019-11-01 20:51 UTC, neSpecc requested changes

2019-11-01 20:51 UTC, neSpecc commented on filter.ts
> +class Filter {
надо разделить эти классы на два файла. В первом (filter.ts) будет абстрактный класс Filter, а во втором (filter-gain.ts) его потомок GainFilter

2019-11-01 20:51 UTC, neSpecc commented on filter.ts
> +const gainFilter: Gain = new Gain();
это для чего? лучше просто экспортировать класс. Конструировать его будет кто-то на уровне выше

2019-11-01 20:51 UTC, neSpecc commented on .idea/.gitignore
> +
эти файлы надо убрать из реквеста

2019-11-01 20:51 UTC, neSpecc commented on filter.ts
> +  constructor(gainNode: any, source: any, destination: any) {
параметры не задокументированы

2019-11-01 20:51 UTC, neSpecc commented on filter.ts
> +    this.gainNode.gain.value = 0.4;
свойства класса надо явно объявить и задокументировать

2019-11-01 20:51 UTC, neSpecc commented on filter.ts
> +    super();
родительский класс лучше вызвать в самом начале конструктора

2019-11-02 10:32 UTC, neSpecc requested changes
- код не встроен в структуру проекта
- параметры классов не объявлены
- абстрактный класс не задокументирован

2019-11-03 16:19 UTC, PolinaShneider commented on filter-gain.ts
> +     * @param source - source of melody
Лучше задокументируй эти параметры перед строчкой `constructor(gainNode: any, source: any, destination: any) {`

WebStorm тебе сам заготовку для JSDoc сгенерировать должен. Параметр `destination` не описан. И все ли они типа `any`, или это пока промежуточная версия?

2019-11-03 19:55 UTC, neSpecc requested changes

2019-11-03 19:55 UTC, neSpecc commented on filter.ts
> + * Create class Filter.
не понятное описание

2019-11-03 19:55 UTC, neSpecc commented on filter-gain.ts
> +    this.gainNode.gain.value = 0.4; // value 0..1 (can be changed dynamically)
свойства не объявлены

2019-11-03 19:55 UTC, neSpecc commented on filter-gain.ts
> +class Gain extends Filter {
```suggestion
class GainFilter extends Filter {
```

2019-11-03 19:55 UTC, neSpecc commented on filter-gain.ts
> +  constructor(gainNode: any, source: any, destination: any) {
почему везде `any`?

2019-11-04 12:04 UTC, neSpecc requested changes

2019-11-04 12:04 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +   * new gain object
```suggestion
   * New gain object
```

2019-11-04 12:04 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +   * source of melody
не понятное описание, которое дублирует название. + надо писать с большой буквы

2019-11-04 12:04 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +  constructor(gainNode: any, source: any, destination: any) {
параметры не задокументированы

2019-11-04 17:30 UTC, neSpecc requested changes

2019-11-04 17:30 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +  public gainNode: any;
уверен, что эти свойства должны быть видны снаружи?

2019-11-04 17:30 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +  /**
```suggestion

  /**
```

2019-11-04 17:30 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +    this.gainNode.gain.value = 0.4; // value 0..1 (can be changed dynamically)
value логично было бы вынести в свойство. Тогда у фильтра были бы методы по изменению этого значения

2019-11-04 20:12 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +  public valueMelody: number;
почему melody?

2019-11-05 05:09 UTC, neSpecc requested changes

2019-11-05 05:09 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +  public source: any;
не хватает обоснования для выбора модификаторов доступа

2019-11-18 16:28 UTC, PolinaShneider commented on src/modules/Track.ts
> +    this.gainFilter = GainFilter;
У тебя есть свойство класса `gainFilter`?

2019-11-18 16:28 UTC, PolinaShneider commented on src/modules/Track.ts
> +    this.gainNode.value = 1;
То же самое. Не вижу свойства класса `gainNode`. `Track` вроде ни от чего не отнаследован

2019-11-18 17:04 UTC, neSpecc requested changes

2019-11-18 17:04 UTC, neSpecc commented on src/modules/Track.ts
> +  private gainFilter: GainFilter;
это только один из доступных фильтров. Почему он является приватным свойством класса трэка? Фильтров может быть 100 разных штук

2019-11-18 17:04 UTC, neSpecc commented on src/modules/filters/filter.ts
> +export default abstract class Filter {
в абстрактый класс надо перенести общие свойства и методы, которые будут у всех фильтров

2019-11-18 17:04 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +   * @param gainNode - new gain object
не понятное описание

2019-11-18 17:04 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +   * @param source - melody knot
не понятное описание

2019-11-18 17:04 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +   * @param destination - place of purpose
не понятное описание

2019-11-18 17:04 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +  constructor(gainNode: any, source: any, destination: any) {
типы не заданы

2019-11-18 17:04 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +    this.gainNode.gain.value = this.value; // value 0..1 (can be changed dynamically)
как изменить значение? должен быть какой-то публичный метод?

2019-11-18 17:04 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +    source.start(0);
уверен, что старт надо делать в конструкторе класса, а не в отдельном методе?

2019-11-19 03:55 UTC, neSpecc requested changes

2019-11-19 03:55 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +  constructor(gainNode: any, source: any, destination: any) {
эти узлы точно надо создавать снаружи и передавать в конструктор? это не относится к бизнес-логике самого фильтра?

2019-11-19 03:55 UTC, neSpecc commented on src/modules/filters/filter-gain.ts
> +  constructor(gainNode: any, source: any, destination: any) {
я про any

2019-11-19 19:59 UTC, ilyamore88 requested changes
Добавь в метод `configure` класса `Track` подключение `gainFilter`, чтобы его можно было потестить.
Переименуй свои файлы в соответствии с остальными: `filter.ts` на `Filter.ts`, `filter-gain.ts` на `GainFilter.ts`.

2019-11-19 19:59 UTC, ilyamore88 commented on src/modules/filters/filter-gain.ts
> +    super();
Конструктор родителя принимает на вход параметр, тут же ты его не передаёшь

2019-11-19 19:59 UTC, ilyamore88 commented on src/modules/filters/filter-gain.ts
> +  private gainNode: any;
```suggestion
  private gainNode: GainNode;
```

2019-11-19 19:59 UTC, ilyamore88 commented on src/modules/Track.ts
> +    this.gainFilter = GainFilter;
```suggestion
    this.gainFilter = gainFilter;
```

2019-11-19 19:59 UTC, ilyamore88 commented on src/modules/filters/filter-gain.ts
> +    gainNode.connect(destination); // connect with place of destination
Давай заменим здесь однострочные комментарии на комментарии вида 
```
/**
 *
 */
```

2019-11-19 19:59 UTC, ilyamore88 commented on src/modules/Track.ts
> +    this.gainFilter.value = 1;
Нелогично выставлять значение у `GainFilter` после выключения инструмента. Я бы добавил для этого публичный set у трека

2019-11-19 19:59 UTC, ilyamore88 commented on src/modules/Track.ts
> +    this.gainFilter.value = 1;
И присваивание какого-то значения громкости должно происходить либо в методе `configure` с попощью вызова соответствующего сеттера у `GainFilter`, либо передаваться в конструктор при создании `GainFilter`

2019-11-19 19:59 UTC, ilyamore88 commented on src/modules/filters/filter-gain.ts
> +    this.gainNode.gain.value = this.value; // value 0..1 (can be changed dynamically)
Нет смысла от такого присваивания в конструкторе, лучше добавь для фильтра сеттер, а в конструктор передавай какое-то дефолтное значение громкости

2019-11-19 19:59 UTC, ilyamore88 commented on src/modules/filters/filter-gain.ts
> +  private source: any;
```suggestion
  private source: OscillatorNode;
```

2019-11-26 10:15 UTC, neSpecc requested changes

2019-11-26 10:15 UTC, neSpecc commented on src/modules/instruments/SineWaveInstrument.ts
> +    this.filter.filterNode.connect(audioContextManager.getAudioContext().destination);
для этого в фильтрах есть метод connect

2019-11-26 10:15 UTC, neSpecc commented on src/modules/Track.ts
> +    this.instrument.lastNode.connect(audioContextManager.getAudioContext().destination);
почему не instrumentSourceNode ?

2019-11-26 14:48 UTC, neSpecc approved these changes

2019-11-26 14:49 UTC, ilyamore88 approved these changes

2019-11-26 14:50 UTC, ilyamore88 commented
Closes #5

2019-11-26 14:50 UTC, merged